Repository aidh-ms/pyAKI, pull requests merged in 2023-06, with the labels that each got.

#19 9 generate docstrings for current state
  .github/workflows/lint_and_test.yml
  .gitignore
  pyAKI/kdigo.py
  pyAKI/preprocessors.py
  pyAKI/probes.py
  setup.py
  tests/test_kdigo.py
  tests/test_mimic.py
Labels: documentation

#8 Implement/lib
  .github/workflows/lint_and_test.yml
  .gitignore
  README.md
  pyAKI/kdigo.py
  pyAKI/preprocessors.py
  pyAKI/probes.py
  pyAKI/utils.py
  setup.py
  tests/test_kdigo.py
  tests/test_mimic.py
Labels: enhancement

#20 Implement/kdigo crea rel and kdigo uo
  .github/dependabot.yml
  .github/workflows/lint_and_test.yml
  .gitignore
  README.md
  kdigo.py
  pyAKI/__init__.py
  pyAKI/kdigo.py
  pyAKI/preprocessors.py
  pyAKI/probes.py
  pyAKI/utils.py
  requirements.txt
  setup.cfg
  setup.py
  tests/test_kdigo.py
  tests/test_mimic.py
Labels: enhancement

#23 Implement/test
  .github/workflows/lint_and_test.yml
  .gitignore
  README.md
  pyAKI/__init__.py
  pyAKI/kdigo.py
  pyAKI/preprocessors.py
  pyAKI/probes.py
  tests/__init__.py
  tests/probes/__init__.py
  tests/probes/test_creatinine_probes.py
  tests/probes/test_urineoutput_probes.py
  tests/test_kdigo.py
  tests/test_mimic.py
Labels: python, tests
